### ISSUE TITLE
Where Codes?

### ISSUE THREAD

**Issue by CSer-Tang-hao** [ppriyank/Fine-grained-Re-Identification#1]

**Comment by CSer-Tang-hao** [comment]
Looking forward to your reply!

**Comment by ppriyank** [comment]
Hello

The paper is currently submitted at a conference. If it gets accepted, I will release the code publicly. Before that, I'm awaiting its results. 
If you are referring to the arxiv paper, it's pretty easy to implement.

**Comment by ppriyank** [comment]
Released
